server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coursedesign?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 767690
    driver-class-name: com.mysql.cj.jdbc.Driver

